"""Utilities for combining patch sets produced by `revert_patch_test`."""

from __future__ import annotations

import argparse
import logging
from collections import defaultdict
from pathlib import Path
from typing import Dict, Tuple, Any, DefaultDict, Set, Callable, Iterable

from utils import load_patches_pickle

logger = logging.getLogger(__name__)
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.INFO)


PatchSetKey = Tuple[Any, ...]
PatchSet = Dict[str, Any]


class PatchCompatibilityGraph:
    """Undirected graph describing compatibility relationships between patch sets."""

    def __init__(self) -> None:
        self._nodes: Dict[PatchSetKey, PatchSet] = {}
        self._edges: DefaultDict[PatchSetKey, Set[PatchSetKey]] = defaultdict(set)

    def add_patch(self, identifier: PatchSetKey, patch: PatchSet) -> None:
        """Register a patch node."""
        self._nodes[identifier] = patch

    def add_compatibility(self, lhs: PatchSetKey, rhs: PatchSetKey) -> None:
        """Record that two patches are compatible."""
        self._edges[lhs].add(rhs)
        self._edges[rhs].add(lhs)

    def connect_compatibilities(self, predicate: Callable[[PatchSetKey, PatchSetKey], bool]) -> None:
        """Evaluate all node pairs and add compatibility edges."""
        identifiers: Iterable[PatchSetKey] = list(self._nodes.keys())
        for idx, lhs in enumerate(identifiers):
            for rhs in identifiers[idx + 1 :]:
                if predicate(lhs, rhs):
                    self.add_compatibility(lhs, rhs)

    @property
    def nodes(self) -> Dict[PatchSetKey, PatchSet]:
        """Return mapping of node identifier to patch payload."""
        return self._nodes

    @property
    def edges(self) -> Dict[PatchSetKey, Set[PatchSetKey]]:
        """Return adjacency list representing compatibility edges."""
        return self._edges


def is_compatiable(key_a: PatchSetKey, key_b: PatchSetKey) -> bool:
    """Return True when two patch sets do not touch the same functions."""

    def extract_functions(key: PatchSetKey) -> Set[str]:
        if len(key) < 4:
            return set()
        funcs = key[3]
        if isinstance(funcs, (list, tuple, set)):
            return {str(name) for name in funcs}
        logger.debug("Unexpected function list type for key %s: %s", key, type(funcs).__name__)
        return set()

    funcs_a = extract_functions(key_a)
    funcs_b = extract_functions(key_b)

    return funcs_a.isdisjoint(funcs_b)


def merge_patches(patches_without_contexts: Dict[PatchSetKey, PatchSet]) -> None:
    """Build a compatibility graph where each node represents an entire patch dictionary."""

    graph = PatchCompatibilityGraph()

    for key_tuple, patch_dict in patches_without_contexts.items():
        if not isinstance(patch_dict, dict):
            logger.warning("Expected dict for patch set %s, got %s", key_tuple, type(patch_dict).__name__)
            continue
        graph.add_patch(key_tuple, patch_dict)

    graph.connect_compatibilities(is_compatiable)

    total_edges = sum(len(neighbors) for neighbors in graph.edges.values()) // 2
    logger.info(
        "Constructed compatibility graph: %d patch sets, %d edges",
        len(graph.nodes),
        total_edges,
    )


def have_joint_trigger(parsed_data: list[dict[str, Any]], bug1: str, bug2: str) -> str | None:
    """
    Return the commit id where both bugs are marked '1|1' or '0.5|1'.

    parsed_data follows the structure produced by prepare_transplant/parse_csv_file:
      [{'commit_id': 'abc123', 'osv_statuses': {'OSV-1': '1|1', ...}}, ...]
    """

    def is_trigger(value: str | None) -> bool:
        return value in {'1|1', '0.5|1'}

    for row in parsed_data:
        statuses = row.get('osv_statuses', {})
        if is_trigger(statuses.get(bug1)) and is_trigger(statuses.get(bug2)):
            return row.get('commit_id')
    return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge patches generated by revert_patch_test.")
    parser.add_argument(
        "cache_file",
        type=Path,
        help="Path to the pickle file storing patches_without_contexts.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cache_file = args.cache_file
    patches_without_contexts = load_patches_pickle(cache_file)
    merge_patches(patches_without_contexts)


if __name__ == "__main__":
    main()
